PROCEDURE SP_CASH_TRANSACTION_TEMP_NIK 

AS

CURR_DATE DATE;

PREV_DATE DATE;

ERRMSG varchar2(200);

--ERRCODE varchar2(20);

BEGIN



--CURR_DATE := '01-JUL-11';   --'01-OCT-10';

--PREV_DATE := '30-JUN-11';   --'30-SEP-10';



CURR_DATE := '20-FEB-15';   --'01-OCT-10';

PREV_DATE := '19-FEB-15';   --'30-SEP-10';





LOOP

  

  IF CURR_DATE IS NULL THEN

    EXIT;

  END IF;

  

  IF CURR_DATE > '20-FEB-2015' THEN

      EXIT;

  END IF;

 

 



  INSERT INTO TRANSACTION_DATA (FUND_ID, SECURITY_CODE, TRANSACTION_DATE, TRANSACTION_TYPE_ID, SALE_PURCHASE_FLAG, QUANTITY, TRANSACTION_PRICE, CONSIDERATION)

  SELECT FUND_ID, SECURITY_CODE, TRUNC(CURR_DATE), TRANSACTION_TYPE_ID, 0, 1, TRANSAMT, TRANSAMT

  FROM

  (SELECT MTMTAB.FUND_ID, MTMTAB.SECURITY_CODE, NVL(NETCASH,0) + NVL(TRANSVAL,0) AS TRANSAMT

  FROM

    (SELECT CURRMTM.FUND_ID AS FUND_ID, CURRMTM.SECURITY_CODE AS SECURITY_CODE, NVL(CURRMTM_VAL,0) - NVL(PREVMTM_VAL,0) AS NETCASH

      FROM

        (SELECT FH.FUND_ID, FH.SECURITY_CODE, MTM_VALUE AS CURRMTM_VAL

          FROM FUND_HOLDINGS FH

        INNER JOIN SECURITY_MASTER SM

          ON (UPPER(SM.SECURITY_CODE) = UPPER(FH.SECURITY_CODE))  

        INNER JOIN FUNDS ON FUNDS.FUND_ID = FH.FUND_ID

        WHERE TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE) AND NVL(FUNDS.OFFSHORE_FLAG,0) in (0,2) AND NVL(FUNDS.active_inactive_flag,0) = 1 AND FUNDS.FUND_ID IN (53)

			   AND UPPER(SECURITY_NAME) = 'CASH') CURRMTM

       LEFT OUTER JOIN

        (SELECT FH.FUND_ID, FH.SECURITY_CODE, MTM_VALUE AS PREVMTM_VAL

          FROM FUND_HOLDINGS FH

        INNER JOIN SECURITY_MASTER SM

          ON (UPPER(SM.SECURITY_CODE) = UPPER(FH.SECURITY_CODE)) 

        INNER JOIN FUNDS ON FUNDS.FUND_ID = FH.FUND_ID

        WHERE TRUNC(EFFECTIVE_DATE) = TRUNC(PREV_DATE) AND NVL(FUNDS.OFFSHORE_FLAG,0) in (0,2) AND NVL(FUNDS.active_inactive_flag,0) = 1 AND FUNDS.FUND_ID IN (53)

           AND UPPER(SECURITY_NAME) = 'CASH') PREVMTM

      ON (CURRMTM.FUND_ID = PREVMTM.FUND_ID AND UPPER(CURRMTM.SECURITY_CODE) = UPPER(PREVMTM.SECURITY_CODE))

    ) MTMTAB



  LEFT OUTER JOIN 



    (SELECT FUND_ID, SUM(NVL(TRAN_COST,0)+NVL(DIVIDENDBONUS_PAYOUT,0)) AS TRANSVAL, TRANSACTION_TYPE_ID

      FROM (SELECT FUND_ID, SECURITY_CODE, 

                  (CASE WHEN (UPPER(TRANSACTION_TYPE_DESCRIPTION) <> 'DIVIDEND' and UPPER(TRANSACTION_TYPE_DESCRIPTION) <> 'BONUS') THEN (CASE WHEN SALE_PURCHASE_FLAG = 0 THEN -1*(Quantity*Transaction_Price) ELSE (Quantity*Transaction_Price) END) ELSE 0 END) AS TRAN_COST,

            (CASE WHEN (UPPER(TRANSACTION_TYPE_DESCRIPTION) = 'DIVIDEND' or UPPER(TRANSACTION_TYPE_DESCRIPTION) = 'BONUS') THEN (CASE WHEN SALE_PURCHASE_FLAG = 0 THEN -1*(Consideration) ELSE (Consideration) END) ELSE 0 END) AS DividendBonus_Payout

            FROM TRANSACTION_DATA TD

            INNER JOIN TRANSACTIONS 

            ON (TD.transaction_type_id = transactions.transaction_type_id)

            WHERE trunc(TRANSACTION_DATE) = TRUNC(CURR_DATE)) TEMP, TRANSACTIONS

    WHERE UPPER(TRANSACTION_TYPE_DESCRIPTION) = 'SUBSCRIPTIONS/REDEMPTIONS'

    GROUP BY Fund_ID, TRANSACTION_TYPE_ID) TDATA



  ON (TDATA.FUND_ID = MTMTAB.FUND_ID)

  WHERE UPPER(MTMTAB.SECURITY_CODE) NOT IN (SELECT UPPER(SECURITY_CODE) 

				     FROM TRANSACTION_DATA INNER JOIN FUNDS ON FUNDS.FUND_ID = TRANSACTION_DATA.FUND_ID

				    WHERE TRUNC(TRANSACTION_DATE) = TRUNC(CURR_DATE)  AND NVL(FUNDS.OFFSHORE_FLAG,0) in (0,2) 

            AND NVL(FUNDS.active_inactive_flag,0) = 1 AND FUNDS.FUND_ID IN (53) ) ) TRANSD, TRANSACTIONS

  WHERE UPPER(TRANSACTION_TYPE_DESCRIPTION) = 'SUBSCRIPTIONS/REDEMPTIONS';



  PREV_DATE := CURR_DATE;

  SELECT MIN(effective_date) INTO CURR_DATE FROM fund_holdings WHERE effective_date > CURR_DATE;





END LOOP;



EXCEPTION 

WHEN OTHERS THEN

ERRMSG:=substr(SQLERRM, 1, 200);

--ERRCODE:=SQLCODE;

UPDATE DAILY_PROCESS_STATS SET STATUS = 'Cash Upload - '||ERRMSG  where UPPER(PROCESS_NAME) = 'ETL STAGE 2';

END SP_CASH_TRANSACTION_TEMP_NIK;