PROCEDURE SP_CASH_HOLDINGS_TEMP_NIK 

AS

CURR_DATE DATE;

DATAREADY NUMBER;

ALLFUNDS NUMBER;

ERRMSG varchar2(200);

--ERRCODE varchar2(20);

BEGIN



CURR_DATE := '09-FEB-15';   --'01-OCT-10';

--PREV_DATE := '30-NOV-11';   --'30-SEP-10';



LOOP

  

  IF CURR_DATE IS NULL THEN

    EXIT;

  END IF;

  

  IF CURR_DATE > '30-JUL-15' THEN

    EXIT;

  END IF;

  

  INSERT INTO FUND_HOLDINGS (FUND_ID, EFFECTIVE_DATE, SECURITY_CODE, QUANTITY, MTM_VALUE, OPTION_POSITION)

  SELECT FH.FUND_ID,FH.EFFECTIVE_DATE, SECURITY_CODE, 1, NAV-HLDG AS CASHMTM, NULL

  FROM (SELECT FUND_ID, EFFECTIVE_DATE, SECURITY_CODE, HLDG

        FROM (SELECT FUND_HOLDINGS.FUND_ID, EFFECTIVE_DATE, SUM(MTM_VALUE) AS HLDG

	      FROM FUND_HOLDINGS INNER JOIN FUNDS ON FUND_HOLDINGS.FUND_ID = FUNDS.FUND_ID

	      WHERE TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE)  AND NVL(FUNDS.OFFSHORE_FLAG,0) in (0,2) and NVL(FUNDS.active_inactive_flag,0) = 1

              GROUP BY FUND_HOLDINGS.FUND_ID,EFFECTIVE_DATE) FUND_HOLD, SECURITY_MASTER 

      WHERE UPPER(SECURITY_NAME) = 'CASH') FH

  INNER JOIN FUND_NAV FN

  ON (FN.FUND_ID = FH.FUND_ID AND TRUNC(FN.VALUE_DATE) = TRUNC(EFFECTIVE_DATE))

  WHERE TRUNC(EFFECTIVE_DATE) NOT IN (SELECT TRUNC(EFFECTIVE_DATE) 

			       FROM FUND_HOLDINGS, FUNDS 

			      WHERE UPPER(SECURITY_CODE) IN (SELECT UPPER(SECURITY_CODE) 

							       FROM SECURITY_MASTER 

						              WHERE UPPER(SECURITY_NAME) = 'CASH') 

                          and NVL(FUNDS.active_inactive_flag,0) = 1 AND FUNDS.FUND_ID IN (66,67)

                          AND FUNDS.fund_id=FUND_HOLDINGS.fund_id) AND FH.FUND_ID IN (66,67);

                          

                          

    SELECT MIN(effective_date) INTO CURR_DATE FROM fund_holdings WHERE effective_date > CURR_DATE;                        

  /*                        

  SELECT MIN(effective_date) INTO CURR_DATE FROM fund_holdings WHERE effective_date > (SELECT MAX(effective_date) FROM fund_holdings, FUNDS WHERE UPPER(security_code)='INCASH000001' 

  AND FUNDS.fund_id=FUND_HOLDINGS.fund_id and NVL(FUNDS.active_inactive_flag,0) = 1 );

    */                      

END LOOP;



EXCEPTION 

WHEN OTHERS THEN

ERRMSG:=substr(SQLERRM, 1, 200);

--ERRCODE:=SQLCODE;



UPDATE DAILY_PROCESS_STATS SET STATUS = 'Cash Holdings - '||ERRMSG  where UPPER(PROCESS_NAME) = 'ETL STAGE 2';

END SP_CASH_HOLDINGS_TEMP_NIK;