PROCEDURE SP_FE_ANALYST_IDEAVIEW (LOGIN_ID IN VARCHAR2,RESEARCH_DT IN DATE, RESULTSET OUT SYS_REFCURSOR)

AS

ANALYSTID VARCHAR2(15);

ISADMIN NUMBER;

EFFECTIVEDT DATE;



BEGIN

SELECT ANALYST_ID,ISADMIN INTO ANALYSTID,ISADMIN FROM KM_ANALYST_MASTER WHERE UPPER(EMAIL) = UPPER(LOGIN_ID);

SELECT MAX(EFFECTIVE_DATE) INTO EFFECTIVEDT FROM KM_SEC_DY_FACTORS;



IF RESEARCH_DT <> EFFECTIVEDT THEN



SELECT MAX(EFFECTIVE_DATE) INTO EFFECTIVEDT FROM KM_SEC_DY_FACTORS WHERE EFFECTIVE_DATE <= RESEARCH_DT ;



END IF;







IF ISADMIN <> 1 THEN

  OPEN RESULTSET FOR



    SELECT 

     KASM.SECURITY_CODE

    ,ISIN.SOURCE_SECURITY_CODE AS ISIN_CODE

    ,ANALYSTID as ANALYST_ID

    ,SM.SECURITY_NAME

    ,S.SECTOR_NAME

    ,KAM.FIRSTNAME||' '|| SUBSTR(KAM.LASTNAME,1,1)||'.' AS ANALYST_NAME

    ,NVL(KSDF.MARKET_CAP,0) AS MARKET_CAP

    ,NVL(KSDF.PRICE,0) AS PRICE

    ,NVL(KSDF.TARGET_PRICE,0) AS TARGET_PRICE

    ,ROUND((NVL(KSDF.TARGET_PRICE,0)/KSDF.PRICE) - 1,8) AS DEVIATION

    ,ROUND((REPORT.RESEARCH_DATE_PRICE/(KSDF.TARGET_PRICE)) - 1,8) AS PROPOSED_RETURNS

    ,ROUND((KSDF.PRICE/REPORT.RESEARCH_DATE_PRICE) - 1,8) AS ACTUAL_RETURNS    

    ,REPORT.REPORT_ID

    ,RECO.RECO_NAME

    ,RESEARCH.RESEARCH_DATE    

    ,ATT.FILENAME AS ATTACHMENT

    ,ATT.FILETIMESTAMP AS ATTACHMENT_TIMESTAMP

    ,EFFECTIVEDT AS EFFECTIVE_DATE

    FROM 

    (SELECT ANALYST_ID,SECURITY_CODE FROM KM_ANALYST_SECURITY_MAPPING WHERE ANALYST_ID = ANALYSTID) KASM

    LEFT JOIN

    KM_SEC_DY_FACTORS KSDF 

    ON KASM.SECURITY_CODE = KSDF.SECURITY_CODE    

    LEFT JOIN 

    (

     SELECT SECURITY_CODE,MAX(RESEARCH_DATE) AS RESEARCH_DATE FROM KM_REPORT_DATA  GROUP BY SECURITY_CODE 

     HAVING MAX(trunc(RESEARCH_DATE)) <= RESEARCH_DT      

    )  RESEARCH ON RESEARCH.SECURITY_CODE = KASM.SECURITY_CODE

    INNER JOIN (SELECT REPORT_ID,RECO_ID,RESEARCH_DATE_PRICE,RESEARCH_DATE,SECURITY_CODE FROM KM_REPORT_DATA where KM_REPORT_DATA.ACT_INACT_FLAG = 1) REPORT ON REPORT.SECURITY_CODE = RESEARCH.SECURITY_CODE AND REPORT.RESEARCH_DATE = RESEARCH.RESEARCH_DATE

    LEFT JOIN KM_RECO_MASTER RECO

    ON REPORT.RECO_ID = RECO.RECO_ID 

    LEFT JOIN 

    (

      SELECT DISTINCT A.REPORT_ID,CASE WHEN A.MULTIPLE > 1 THEN '-1' ELSE B.FILENAME END AS FILENAME,

      CASE WHEN A.MULTIPLE > 1 THEN '-1' ELSE B.FILETIMESTAMP END AS FILETIMESTAMP from

      (SELECT COUNT(REPORT_ID) MULTIPLE,REPORT_ID FROM KM_REPORT_ATTACHMENT GROUP BY REPORT_ID) A

      INNER JOIN KM_REPORT_ATTACHMENT B ON B.REPORT_ID = A.REPORT_ID

    ) ATT ON REPORT.REPORT_ID = ATT.REPORT_ID

    INNER JOIN

    SECURITY_MASTER SM

    ON SM.SECURITY_CODE = KASM.SECURITY_CODE

    INNER JOIN 

    SECURITY_CODE_BBISIN_INTMDT ISIN

    ON SM.SECURITY_CODE = ISIN.BM_CODE

    INNER JOIN 

    SECURITY_SECTOR_MAPPING SSM

    ON SSM.SECURITY_CODE = KASM.SECURITY_CODE

    INNER JOIN SECTORS S

    ON SSM.SECTOR_ID = S.SECTOR_ID

    INNER JOIN 

    (

      SELECT FIRSTNAME,LASTNAME,ANALYST_ID FROM KM_ANALYST_MASTER WHERE ISADMIN <> 1

    ) KAM

    ON KAM.ANALYST_ID = KASM.ANALYST_ID AND KAM.ANALYST_ID = ANALYSTID

    WHERE KSDF.EFFECTIVE_DATE = EFFECTIVEDT;          

ELSE

  OPEN RESULTSET FOR

    SELECT 

     KIU.SECURITY_CODE

    ,ISIN.SOURCE_SECURITY_CODE AS ISIN_CODE

    ,ANALYSTID as ANALYST_ID

    ,SM.SECURITY_NAME

    ,S.SECTOR_NAME

    ,KAM.FIRSTNAME||' '|| SUBSTR(KAM.LASTNAME,1,1)||'.' AS ANALYST_NAME

    ,NVL(KSDF.MARKET_CAP,0) AS MARKET_CAP

    ,NVL(KSDF.PRICE,0) AS PRICE

    ,NVL(KSDF.TARGET_PRICE,0) AS TARGET_PRICE

    ,ROUND((NVL(KSDF.TARGET_PRICE,0)/KSDF.PRICE) - 1,8) AS DEVIATION

    ,ROUND((REPORT.RESEARCH_DATE_PRICE/(KSDF.TARGET_PRICE)) - 1,8) AS PROPOSED_RETURNS

    ,ROUND((KSDF.PRICE/REPORT.RESEARCH_DATE_PRICE) - 1,8) AS ACTUAL_RETURNS  

    ,REPORT.REPORT_ID

    ,RECO.RECO_NAME

    ,RESEARCH.RESEARCH_DATE  

    ,ATT.FILENAME AS ATTACHMENT

    ,ATT.FILETIMESTAMP AS ATTACHMENT_TIMESTAMP

    ,EFFECTIVEDT AS EFFECTIVE_DATE

    FROM 

    KM_INVESTMENT_UNIVERSE KIU

    LEFT JOIN 

    KM_ANALYST_SECURITY_MAPPING KASM

    ON KIU.SECURITY_CODE = KASM.SECURITY_CODE

    LEFT JOIN

    KM_SEC_DY_FACTORS KSDF 

    ON KIU.SECURITY_CODE = KSDF.SECURITY_CODE

    LEFT JOIN 

    (

     SELECT SECURITY_CODE,MAX(RESEARCH_DATE) AS RESEARCH_DATE FROM KM_REPORT_DATA  GROUP BY SECURITY_CODE 

     HAVING MAX(trunc(RESEARCH_DATE)) <= RESEARCH_DT      

    )  RESEARCH ON RESEARCH.SECURITY_CODE = KIU.SECURITY_CODE

    INNER JOIN (SELECT REPORT_ID,RECO_ID,RESEARCH_DATE_PRICE,RESEARCH_DATE,SECURITY_CODE FROM KM_REPORT_DATA where KM_REPORT_DATA.ACT_INACT_FLAG = 1) REPORT ON REPORT.SECURITY_CODE = RESEARCH.SECURITY_CODE AND REPORT.RESEARCH_DATE = RESEARCH.RESEARCH_DATE

    LEFT JOIN KM_RECO_MASTER RECO

    ON REPORT.RECO_ID = RECO.RECO_ID 

   LEFT JOIN 

   (

     SELECT DISTINCT A.REPORT_ID,CASE WHEN A.MULTIPLE > 1 THEN '-1' ELSE B.FILENAME END AS FILENAME,

      CASE WHEN A.MULTIPLE > 1 THEN '-1' ELSE B.FILETIMESTAMP END AS FILETIMESTAMP from

      (SELECT COUNT(REPORT_ID) MULTIPLE,REPORT_ID FROM KM_REPORT_ATTACHMENT GROUP BY REPORT_ID) A

      INNER JOIN KM_REPORT_ATTACHMENT B ON B.REPORT_ID = A.REPORT_ID

    ) ATT ON REPORT.REPORT_ID = ATT.REPORT_ID

    INNER JOIN

    SECURITY_MASTER SM

    ON SM.SECURITY_CODE = KIU.SECURITY_CODE

    INNER JOIN 

    SECURITY_CODE_BBISIN_INTMDT ISIN

    ON SM.SECURITY_CODE = ISIN.BM_CODE

    INNER JOIN 

    SECURITY_SECTOR_MAPPING SSM

    ON SSM.SECURITY_CODE = KIU.SECURITY_CODE

    INNER JOIN SECTORS S

    ON SSM.SECTOR_ID = S.SECTOR_ID

    INNER JOIN 

    (

      SELECT FIRSTNAME,LASTNAME,ANALYST_ID FROM KM_ANALYST_MASTER WHERE ISADMIN = 1

    ) KAM

    ON KAM.ANALYST_ID = KASM.ANALYST_ID   

    WHERE KSDF.EFFECTIVE_DATE = EFFECTIVEDT;

    

END IF;

END SP_FE_ANALYST_IDEAVIEW;

