PROCEDURE SP_FE_FUNDS_CASH_HOLDING(LOGINID IN VARCHAR2,RES OUT sys_refcursor)

AS

BEGIN



   INSERT INTO USERSACCESS_LOG (LOGIN_ID,ACTIVITY_DATE,ACTIVITY,PAGE_NAME)

   VALUES (LOGINID,SYSDATE,'KM : Fund Estimates' , 'Fund Estimates');



OPEN RES FOR



SELECT   CASE WHEN UPPER(F.FM_ID) = UPPER(LOGINID) OR UPPER(F.FM_ID2)= UPPER(LOGINID) THEN 1 ELSE 2 END AS RNK,NVL(CASH_HOLDING,0)CASH_HOLDING

        ,F.FUND_NAME FUNDNAME

        ,NVL(KCH.MORNING_IO_FLOW,0) as Morning_IO_FLOW

        ,F.FUND_ID

        ,KCH.CURRENT_EFFECTIVE_DATE as curr_Effective_Date 

        ,KCH.PREVIOUS_EFFECTIVE_DATE as Prev_effective_date

        ,NVL(KCH.EVENING_IO_FLOW,0) as Evening_IO_FLOW

  FROM KM_CASH_HOLDINGS KCH

  INNER JOIN FUNDS F

  ON KCH.FUND_ID = F.FUND_ID

  WHERE KCH.CURRENT_EFFECTIVE_DATE = (SELECT MAX(CURRENT_EFFECTIVE_DATE) FROM KM_CASH_HOLDINGS) and F.FUND_TYPE in ('EQ','HYB')

  ORDER BY RNK;





/*

  SELECT 1 AS RNK,NVL(CASH_HOLDING,0)CASH_HOLDING

        ,F.FUND_NAME FUNDNAME

        ,NVL(KCH.MORNING_IO_FLOW,0) as Morning_IO_FLOW

        ,F.FUND_ID

        ,KCH.CURRENT_EFFECTIVE_DATE as curr_Effective_Date 

        ,KCH.PREVIOUS_EFFECTIVE_DATE as Prev_effective_date

        ,NVL(KCH.EVENING_IO_FLOW,0) as Evening_IO_FLOW

  FROM KM_CASH_HOLDINGS KCH

  INNER JOIN 

  FUNDS F

  ON KCH.FUND_ID = F.FUND_ID

  WHERE KCH.CURRENT_EFFECTIVE_DATE = (SELECT MAX(CURRENT_EFFECTIVE_DATE) FROM KM_CASH_HOLDINGS) and F.FUND_TYPE in ('EQ','HYB')

  AND (UPPER(F.FM_ID) = UPPER(LOGINID) OR UPPER(F.FM_ID2)= UPPER(LOGINID))

  UNION

  SELECT 2 AS RNK,NVL(CASH_HOLDING,0)CASH_HOLDING

        ,F.FUND_NAME FUNDNAME

        ,NVL(KCH.MORNING_IO_FLOW,0) as Morning_IO_FLOW

        ,F.FUND_ID

        ,KCH.CURRENT_EFFECTIVE_DATE as curr_Effective_Date 

        ,KCH.PREVIOUS_EFFECTIVE_DATE as Prev_effective_date

        ,NVL(KCH.EVENING_IO_FLOW,0) as Evening_IO_FLOW

  FROM KM_CASH_HOLDINGS KCH

  INNER JOIN 

  FUNDS F

  ON KCH.FUND_ID = F.FUND_ID

  WHERE KCH.CURRENT_EFFECTIVE_DATE = (SELECT MAX(CURRENT_EFFECTIVE_DATE) FROM KM_CASH_HOLDINGS) and F.FUND_TYPE in ('EQ','HYB')

  AND (UPPER(F.FM_ID) <> UPPER(LOGINID) OR UPPER(F.FM_ID2) <> UPPER(LOGINID))

  ORDER BY RNK;

  */

END;

