PROCEDURE SP_FE_ANALYST_SECURITYVIEW (LOGIN_ID IN VARCHAR2,RESULTSET OUT SYS_REFCURSOR)

AS

ANALYSTID VARCHAR2(15);

BEGIN

SELECT ANALYST_ID INTO ANALYSTID FROM KM_ANALYST_MASTER WHERE UPPER(EMAIL) = UPPER(LOGIN_ID);



OPEN RESULTSET FOR



SELECT

 KIU.SECURITY_CODE

,ANALYSTID as ANALYST_ID

,SM.SECURITY_NAME

,S.SECTOR_NAME

,KAM.FIRSTNAME||' '|| SUBSTR(KAM.LASTNAME,1,1)||'.' AS ANALYST_NAME

,NVL(KSDF.PRICE,0) AS PRICE

,NVL(KSDF.TARGET_PRICE,0) AS TARGET_PRICE

,ROUND((NVL(KSDF.TARGET_PRICE,0)/KSDF.PRICE) - 1,8) AS DEVIATION

,NVL(KSDF.BLOOM_TARGET_PRICE,0) AS BLOOM_TARGET_PRICE

,ROUND((NVL(KSDF.BLOOM_TARGET_PRICE,0)/KSDF.PRICE) - 1,8) AS BLOOM_TARGET_DEV

,NVL(KSDF.MARKET_CAP,0) AS MARKET_CAP

,NVL(KSA.ALERT_PRICE,-1) AS SET_PRICE

FROM 

KM_INVESTMENT_UNIVERSE KIU

LEFT JOIN 

KM_ANALYST_SECURITY_MAPPING KASM

ON KIU.SECURITY_CODE = KASM.SECURITY_CODE

LEFT JOIN

KM_SEC_DY_FACTORS KSDF 

ON KIU.SECURITY_CODE = KSDF.SECURITY_CODE

INNER JOIN

SECURITY_MASTER SM

ON SM.SECURITY_CODE = KIU.SECURITY_CODE

INNER JOIN 

SECTORS S

ON SM.SECTOR_ID = S.SECTOR_ID

INNER JOIN 

(

  SELECT * FROM KM_ANALYST_MASTER WHERE ISADMIN <> 1

) KAM

ON KAM.ANALYST_ID = KASM.ANALYST_ID

LEFT JOIN

(SELECT * FROM KM_SECPRICE_ALERTS WHERE ANALYST_ID = ANALYSTID) KSA

ON  KASM.SECURITY_CODE = KSA.SECURITY_CODE

WHERE KSDF.EFFECTIVE_DATE = (SELECT MAX(EFFECTIVE_DATE) FROM KM_SEC_DY_FACTORS);





END SP_FE_ANALYST_SECURITYVIEW;

