procedure SP_FE_MODEL_MAX_DATE(RESULTSET OUT SYS_REFCURSOR)

AS

FROM_DATE DATE;

TO_DATE DATE;

BEGIN



SELECT MAX(EFFECTIVE_DATE) INTO TO_DATE FROM FUND_HOLDINGS;



SELECT MAX(EFFECTIVE_DATE) INTO FROM_DATE FROM FUND_HOLDINGS WHERE EFFECTIVE_DATE <= ADD_MONTHS(TO_DATE,-1);



OPEN RESULTSET FOR

select TO_DATE as Max_Date, FROM_DATE AS MIN_DATE from dual;



END SP_FE_MODEL_MAX_DATE;