PROCEDURE SP_FE_REPORT_ATTACHMENTS (REP_ID IN NUMBER,RESULTSET OUT SYS_REFCURSOR)

AS

BEGIN

OPEN RESULTSET FOR

SELECT ATTACHMENT_ID,FILENAME,FILETIMESTAMP FROM KM_REPORT_ATTACHMENT WHERE REPORT_ID = REP_ID; 

END SP_FE_REPORT_ATTACHMENTS;