PROCEDURE SP_FE_KM_CORP(RESULTSET OUT SYS_REFCURSOR)

AS

BEGIN 



OPEN RESULTSET FOR



SELECT DISTINCT ISIN_NUMBER,COMPANY_NAME,EFFECTIVE_DATE AS DECLARED_DATE,CATEGORY,HEADER AS DESCRIPTION FROM KM_CORP_ACTION

WHERE EFFECTIVE_DATE >= ADD_MONTHS(sysdate,-3);



END;