PROCEDURE SP_FE_TRADE_RECO (FUNDID in number,MODELID in number,RUN_DATE in Date,ResultSet out SYS_REFCURSOR)

as



CHECK_EXIST number;



BEGIN

  SELECT count(*) into CHECK_EXIST FROM trade_reco WHERE fund_id= fundid and model_id= modelid and effective_date= run_date;



  if (CHECK_EXIST = 0) then

  

    SP_TRADE_RECO(fundid, modelid, run_date);

    

  end if;

  

 open ResultSet for 

   

   SELECT 

      FUND_ID,MODEL_ID,TR.EFFECTIVE_DATE,TR.SECURITY_CODE AS SECURITY_CODE,

      SM.SECURITY_NAME AS SECURITY_NAME, SECT.SECTOR_NAME AS SECTOR_NAME,

      FUND_QUANTITY, FUND_MTM, FUND_AUM, FUND_WEIGHT,

      MODEL_QUANTITY,MODEL_MTM,MODEL_AUM,MODEL_WEIGHT,

      ACTIVE_WEIGHT,SALE_PURCHASE_FLAG,

      TRANSACTION_QUANTITY, PRICE , CONSIDERATION

      FROM TRADE_RECO TR, SECURITY_MASTER SM , SECTORS SECT

      WHERE SM.SECURITY_CODE=TR.SECURITY_CODE AND 

      SM.SECTOR_ID=SECT.SECTOR_ID AND TR.FUND_ID=FUNDID 

      AND TR.MODEL_ID=MODELID AND TRUNC(TR.EFFECTIVE_DATE)=TRUNC(RUN_DATE);



END SP_FE_TRADE_RECO; 

