PROCEDURE SP_FE_HOLDINGS_RMF (RUN_DATE in Date,LOGINID IN VARCHAR2,BUCKETNAME IN VARCHAR2,ResultSet out SYS_REFCURSOR)

AS

CHECK_EXIST number;

BUCKET_NAME_CHECK NVARCHAR2(50);

BEGIN



  select count(*) into CHECK_EXIST from FUND_HOLDINGS where TRUNC(effective_date)=TRUNC(RUN_DATE);

  

  BUCKET_NAME_CHECK := bucketname;

  /*IF(bucketname = 'NA') THEN

  BUCKET_NAME_CHECK := 'DEFMATURITYBUCKET';

  END IF;*/

  

   

  if (CHECK_EXIST <> 0) then

  

     open ResultSet for 



      SELECT F.FUND_NAME AS SCHEME_NAME,NVL(FIM.DISPLAY_ASSET_CLASS,FIM.ASSET_CLASS) AS ASSET_CLASS

      ,SM.SECURITY_NAME,ROUND(NVL(FND.QUANTITY,0)*NVL(FNDFI.FACE_VALUE_PER_UNIT,0),8) AS FACE_VALUE

      ,FND.TOTAL_MARKET_VALUE AS MARKET_VALUE,NVL(FND.MODIFIED_DURATION,0) AS MODIFIED_DURATION

      ,ROUND(FND.RESIDUAL_MATURITY_PERIOD_DAYS/365,8) AS MATURITY_PERIOD

      ,NVL(FND.VALUATION_YIELD,0) AS VALUATION_YIELD,F.SHORT_NAME AS SCHEME_SHORT_NAME

      ,F.FUND_SUBTYPE AS SCHEME_TYPE,F.START_DATE AS SCHEME_START_DATE,F.END_DATE AS SCHEME_END_DATE

      , FND.FINAL_MATURITY AS FINAL_MATURITY,FND.MATURITY_DATE AS MATURITY_PC_DATE

      ,FNDFI.COUPON_RATE AS INTEREST_RATE,FND.RATING AS PRIMARYRATING

      ,FIM.ISSUER AS ISSUER,FND.QUANTITY AS QUANTITY,ROUND(FND.TOTAL_MARKET_VALUE/FN.NAV,8) AS WEIGHT

      ,ROUND(FND.TOTAL_MARKET_VALUE/FN.NAV,8)*FNDFI.RESIDUAL_MATURITY_PERIOD_DAYS AS WTD_AVG_MAT

      ,FND.CBV_MATRIX AS MATRIX_USED,FNDFI.ILLIQUIDTY_BPS AS ILLIQUIDTY_BPS,FNDFI.DV01 AS DV01

      ,FNDFI.ACCRUAL AS ACCRUAL,FNDFI.ISSUER_RATING AS ISSUER_RATING, FIM.ISSUER_CLASS_GROUP

      ,FIM.ISSUER_CLASS_OWNER, FIM.ISSUER_CLASS_SECTOR, FIM.ISSUER_CLASS_SUBSECTOR

      ,FND.FUND_SHORT_NAME AS DB_SCHEME_CODE,FND.CURR_MKT_PRICE AS MKT_RATE

      ,FNDFI.PREVIOUS_IP_DATE AS PREV_INTEREST_DATE, FNDFI.NEXT_IP_DATE AS NEXT_INTEREST_DATE

      ,FND.ACCRUED_INTEREST AS ACCRUED_INTEREST,FND.SECTOR_NAME AS RMLF_INDUSTRY_NEW

      ,FNDFI.AMFI_SECTOR AS RMLF_SECTOR_NEW,NVL(FND.YIELD_CRISIL,0) AS CRISIL_YIELD,NVL(FND.YIELD_ICRA,0) AS ICRA_YIELD

      ,NVL(FND.MODIFIED_DUR_CRISIL,0) AS CRISIL_MDUR, NVL(FND.MODIFIED_DUR_ICRA,0) AS ICRA_MDUR

      ,FNDFI.MATURITY_TYPE AS MATURITY_TYPE

      ,NVL(FND.PREVIOUS_DAY_VAL_YIELD,0) AS PREV_DAY_YIELD,NVL(bm.bucket_name,'Above Max.') as BUCKET_NAME,

      CASE

      WHEN SM.SECURITY_NAME IN ('OTHER RECEIVABLES')

      THEN TO_CHAR(FND.HOLDING_DATE,'MON')

        || ' '

        ||TO_CHAR(FND.HOLDING_DATE,'YYYY')

      ELSE TO_CHAR(FND.FINAL_MATURITY,'MON')

        ||' '

        ||TO_CHAR(FND.FINAL_MATURITY,'YYYY')

      END AS MONTH ,

      CASE

        WHEN SM.SECURITY_NAME IN ('OTHER RECEIVABLES')

        THEN DECODE(TO_CHAR(FND.HOLDING_DATE,'Q'),'1','MAR','2','JUN','3','SEP',

        '4','DEC')

        ||' '

        || TO_CHAR(TRUNC(FND.HOLDING_DATE),'YYYY')

      ELSE DECODE(TO_CHAR(TRUNC(FND.FINAL_MATURITY),'Q'),'1','MAR','2','JUN','3',

        'SEP','4','DEC')

        ||' '

        || TO_CHAR(TRUNC(FND.FINAL_MATURITY),'YYYY')

      END AS QUARTER ,

    CASE

      WHEN SM.SECURITY_NAME IN ('OTHER RECEIVABLES')

      THEN TO_CHAR(FND.HOLDING_DATE,'YYYY')

      ELSE TO_CHAR(FND.FINAL_MATURITY,'YYYY')

    END AS YEAR ,

    CASE

      WHEN SM.SECURITY_NAME IN ('OTHER RECEIVABLES')

      THEN TO_CHAR(FND.HOLDING_DATE,'MON')

        || ' '

        ||TO_CHAR(FND.HOLDING_DATE,'YYYY')

      ELSE TO_CHAR(FND.MATURITY_DATE,'MON')

        ||' '

        ||TO_CHAR(FND.MATURITY_DATE,'YYYY')

    END AS MONTH_PC ,

    CASE

      WHEN SM.SECURITY_NAME IN ('OTHER RECEIVABLES')

      THEN DECODE(TO_CHAR(FND.HOLDING_DATE,'Q'),'1','MAR','2','JUN','3','SEP',

        '4','DEC')

        ||' '

        || TO_CHAR(TRUNC(FND.HOLDING_DATE),'YYYY')

      ELSE (DECODE(TO_CHAR(TRUNC(FND.MATURITY_DATE),'Q'),'1','MAR','2',

        'JUN','3','SEP','4','DEC')

        ||' '

        || TO_CHAR(TRUNC(FND.MATURITY_DATE),'YYYY'))

    END AS QUARTER_PC ,

    CASE

      WHEN SM.SECURITY_NAME IN ('OTHER RECEIVABLES')

      THEN TO_CHAR(FND.HOLDING_DATE,'YYYY')

      ELSE TO_CHAR(FND.MATURITY_DATE,'YYYY')

    END                                    AS YEAR_PC 

        FROM 

        (SELECT /*+ index(fund_holdings_SRC IDX_HLDGS_SRC_FND_DATE) */ * FROM fund_holdings_SRC WHERE TRUNC(HOLDING_DATE) = TRUNC(RUN_DATE) AND 

        SCHEMECODE IN (SELECT FUND_ID FROM FUND_USER_MAPPING WHERE LOGIN_ID = LOGINID)) FND

        LEFT JOIN (SELECT /*+ index(fund_holdings_fi UK_HLDGSFI_EFF_DATE) */ * FROM fund_holdings_fi WHERE TRUNC(EFFECTIVE_DATE) = TRUNC(RUN_DATE)AND 

        FUND_ID IN (SELECT FUND_ID FROM FUND_USER_MAPPING WHERE LOGIN_ID = LOGINID)) FNDFI

        ON FND.SCHEMECODE = FNDFI.fund_id and FND.security_code = FNDFI.security_code

        INNER JOIN (select * from funds where normal_flag <> 1) f on FND.SCHEMECODE = f.fund_id

        INNER JOIN (SELECT * FROM FUND_NAV WHERE TRUNC(VALUE_DATE) = TRUNC(RUN_DATE)) FN ON FN.FUND_ID = FND.SCHEMECODE

        INNER JOIN security_master sm ON sm.security_code = FND.security_code

        LEFT JOIN fi_master fim ON FND.security_code = FIM.security_code

        LEFT JOIN bucket_master bm ON

        (

            (upper(BM.BASE_DATA_FIELD) = 'MATURITY' AND BM.BUCKET_CLASS_NAME = BUCKET_NAME_CHECK

            AND FNDFI.RESIDUAL_MATURITY_PERIOD_DAYS >= TO_NUMBER(BM.MIN_VALUE)

            AND FNDFI.RESIDUAL_MATURITY_PERIOD_DAYS < TO_NUMBER(BM.MAX_VALUE))

            OR

            (upper(BM.BASE_DATA_FIELD) = 'MATURITYDATE' AND BM.BUCKET_CLASS_NAME = BUCKET_NAME_CHECK

            AND TRUNC(FND.FINAL_MATURITY) >= TRUNC(BM.MIN_DATE)

            AND TRUNC(FND.FINAL_MATURITY) < TRUNC(BM.MAX_DATE))

        );

      END IF;  

  

  END SP_FE_HOLDINGS_RMF;

  