PROCEDURE SP_FE_ANALYSTVIEW_COVERAGE(FUNDID IN NUMBER,LOGIN_ID IN VARCHAR2,RESULTSET1 OUT sys_refcursor,RESULTSET2 OUT sys_refcursor,RESULTSET3 OUT sys_refcursor,RESULTSET4 OUT sys_refcursor)

AS

ANALYSTID VARCHAR2(15);

ISFM NUMBER;

ISADM NUMBER;



BEGIN





INSERT INTO USERSACCESS_LOG (LOGIN_ID,ACTIVITY_DATE,ACTIVITY,PAGE_NAME)

   VALUES (LOGIN_ID,SYSDATE,'Analyst Coverage' , 'Analyst Coverage');



SELECT ANALYST_ID INTO ANALYSTID FROM KM_ANALYST_MASTER WHERE UPPER(EMAIL) = UPPER(LOGIN_ID);



SELECT COUNT(*) INTO ISFM FROM FUNDS WHERE /*UPPER(FM_ID) = UPPER(LOGIN_ID)*/ 1=0;



SELECT ANALYST_ID,ISADMIN,IS_FM INTO ANALYSTID,ISADM,ISFM FROM KM_ANALYST_MASTER WHERE UPPER(EMAIL) = UPPER(LOGIN_ID);



IF ISFM = 1 THEN



OPEN RESULTSET1 FOR

/*

select KMD.SECURITY_CODE,SM.SECURITY_NAME,NVL(S.SECTOR_NAME,'N.A') SECTOR_NAME,NVL(KRM.RECO_NAME,'N.A') RECO_NAME,

NVL(KMD.TARGET_PRICE,0) TARGET_PRICE,NVL(KMD.PRICE,0) PRICE  

from 

FUND_HOLDINGS FH

LEFT JOIN 

KM_SEC_DY_FACTORS KMD

ON FH.SECURITY_CODE = KMD.SECURITY_CODE AND FH.EFFECTIVE_DATE = KMD.EFFECTIVE_DATE

LEFT JOIN

SECURITY_MASTER SM

ON KMD.SECURITY_CODE = SM.SECURITY_CODE

LEFT JOIN KM_RECO_MASTER KRM

ON KMD.RECO_ID = KRM.RECO_ID

INNER JOIN SECTORS S

ON SM.SECTOR_ID = S.SECTOR_ID

WHERE FH.EFFECTIVE_DATE = (SELECT MAX(EFFECTIVE_DATE) FROM KM_SEC_DY_FACTORS) 

AND FUND_ID = FUNDID;*/



select KMD.SECURITY_CODE,SM.SECURITY_NAME,S.SECTOR_NAME,KRM.RECO_NAME,NVL(KMD.TARGET_PRICE,0) AS TARGET_PRICE,NVL(KMD.PRICE,0) AS PRICE

from KM_SEC_DY_FACTORS KMD

LEFT JOIN

SECURITY_MASTER SM

ON KMD.SECURITY_CODE = SM.SECURITY_CODE

LEFT JOIN KM_RECO_MASTER KRM

ON KMD.RECO_ID = KRM.RECO_ID

INNER JOIN SECTORS S

ON SM.SECTOR_ID = S.SECTOR_ID

WHERE KMD.EFFECTIVE_DATE = (SELECT MAX(EFFECTIVE_DATE) FROM KM_SEC_DY_FACTORS);





ELSE 



OPEN RESULTSET1 FOR



select KMD.SECURITY_CODE,SM.SECURITY_NAME,S.SECTOR_NAME,KRM.RECO_NAME,NVL(KMD.TARGET_PRICE,0) AS TARGET_PRICE,NVL(KMD.PRICE,0) AS PRICE  

from KM_SEC_DY_FACTORS KMD

LEFT JOIN

SECURITY_MASTER SM

ON KMD.SECURITY_CODE = SM.SECURITY_CODE

LEFT JOIN KM_RECO_MASTER KRM

ON KMD.RECO_ID = KRM.RECO_ID

INNER JOIN SECTORS S

ON SM.SECTOR_ID = S.SECTOR_ID

INNER JOIN (SELECT * FROM KM_ANALYST_SECURITY_MAPPING WHERE ANALYST_ID = ANALYSTID) KASM

ON KASM.SECURITY_CODE = KMD.SECURITY_CODE

WHERE KMD.EFFECTIVE_DATE = (SELECT MAX(EFFECTIVE_DATE) FROM KM_SEC_DY_FACTORS);  



END IF;  





IF ISFM = 1 THEN



OPEN RESULTSET2 FOR



 SELECT sm.SECURITY_NAME,NVL(bvc.TARGET_PRICE,0)TARGET_PRICE,NVL(bvc.PREVIOUS_SAY,'NA') AS PREVIOUS_SAY,NVL(bvc.RECO_CHANGE,'NA')RECO_CHANGE

 FROM 

 FUND_HOLDINGS FH

  INNER JOIN 

  KM_BROKER_VIEW_CHANGE BVC

 ON FH.SECURITY_CODE = BVC.SECURITY_CODE AND FH.EFFECTIVE_DATE = BVC.EFFECTIVE_DATE 

 INNER JOIN

 SECURITY_MASTER sm 

  ON FH.SECURITY_CODE = SM.SECURITY_CODE 

WHERE TRUNC(FH.EFFECTIVE_DATE) = (select max(EFFECTIVE_DATE) from KM_BROKER_VIEW_CHANGE) AND FH.FUND_ID = FUNDID;



ELSE



OPEN RESULTSET2 FOR



 SELECT sm.SECURITY_NAME,NVL(bvc.TARGET_PRICE,0)TARGET_PRICE,NVL(bvc.PREVIOUS_SAY,'NA') AS PREVIOUS_SAY,NVL(bvc.RECO_CHANGE,'NA')RECO_CHANGE

 FROM 

 SECURITY_MASTER sm 

 INNER JOIN KM_BROKER_VIEW_CHANGE bvc

 ON sm.SECURITY_CODE = bvc.SECURITY_CODE

WHERE TRUNC(bvc.EFFECTIVE_DATE) = (select max(EFFECTIVE_DATE) from KM_BROKER_VIEW_CHANGE);



END IF;





IF ISFM = 1 THEN



OPEN RESULTSET3 FOR



/*SELECT sm.SECURITY_NAME as Security_name,

ca.CA_NAME AS TYPE_OF_CA,ca.DECLARED_DATE DECLARED_DATE,ca.EXECUTION_DATE EX_DATE,ca.PRICE,ca.RATIO

FROM 

KM_CORPORATE_ACTIONS ca 

INNER JOIN 

FUND_HOLDINGS FH

ON ca.SECURITY_CODE = FH.SECURITY_CODE AND ca.EFFECTIVE_DATE = FH.EFFECTIVE_DATE

INNER JOIN

SECURITY_MASTER sm ON sm.SECURITY_CODE=ca.SECURITY_CODE 

WHERE FH.EFFECTIVE_DATE = (SELECT MAX(EFFECTIVE_DATE) FROM FUND_HOLDINGS) AND FH.FUND_ID = FUNDID;*/

SELECT DISTINCT ISIN_NUMBER,COMPANY_NAME,EFFECTIVE_DATE AS DECLARED_DATE,CATEGORY,HEADER AS DESCRIPTION FROM KM_CORP_ACTION

WHERE EFFECTIVE_DATE >= ADD_MONTHS(sysdate,-3);

ELSE



OPEN RESULTSET3 FOR



/*SELECT sm.SECURITY_NAME as Security_name,

ca.CA_NAME AS TYPE_OF_CA,ca.DECLARED_DATE DECLARED_DATE,ca.EXECUTION_DATE EX_DATE,ca.PRICE,ca.RATIO

FROM 

KM_CORPORATE_ACTIONS ca 

INNER JOIN 

SECURITY_MASTER sm ON sm.SECURITY_CODE=ca.SECURITY_CODE

WHERE CA.EFFECTIVE_DATE = (SELECT MAX(EFFECTIVE_DATE) FROM KM_CORPORATE_ACTIONS);*/

SELECT DISTINCT ISIN_NUMBER,COMPANY_NAME,EFFECTIVE_DATE AS DECLARED_DATE,CATEGORY,HEADER AS DESCRIPTION FROM KM_CORP_ACTION

WHERE EFFECTIVE_DATE >= ADD_MONTHS(sysdate,-3);

END IF;





OPEN RESULTSET4 FOR



SELECT distinct NVL(it.SECURITY_CODE,'NA') AS SECURITY_CODE,

  it.REPORTING_DATE,

  it.REPORTED_BY,

  it.SECURITY_NAME,

  it.ACQSELL,

  it.BS_FLAG,

  it.MARKET_SALE,

  nvl(it.QTY,0) as QTY,

  it.START_DATE,

  it.END_DATE,

  NVL(it.SHARE_VALUE,0) as SHARE_VALUE,

  nvl(it.PRICE,0) as PRICE FROM KM_INSIDER_TRADES it ;







END SP_FE_ANALYSTVIEW_COVERAGE;

