PROCEDURE SP_FE_FETCHALLSEC (RESULTSET OUT SYS_REFCURSOR,LOGINID in varchar2)

AS

BEGIN



INSERT INTO USERSACCESS_LOG (LOGIN_ID,ACTIVITY_DATE,ACTIVITY,PAGE_NAME)

   VALUES (LOGINID,SYSDATE,'Security Estimate' , 'Security Estimate');

   

  OPEN RESULTSET FOR

    SELECT SM.SECURITY_CODE,TRIM(SECURITY_NAME) as SECURITY_NAME 

    FROM 

    KM_INVESTMENT_UNIVERSE KIU

    INNER JOIN

    SECURITY_MASTER SM 

    ON KIU.SECURITY_CODE = SM.SECURITY_CODE

    WHERE KIU.INV_UNV_FLAG = 1;

END SP_FE_FETCHALLSEC;

