PROCEDURE SP_FE_IDEAVIEW_SECURITIES (

    LOGIN_ID IN VARCHAR2,

    RESULTSET OUT SYS_REFCURSOR)

AS

  ANALYSTID VARCHAR2(15);

  ISADMIN   NUMBER;

  EFFECTIVEDT DATE;

BEGIN

  SELECT ANALYST_ID,

    ISADMIN

  INTO ANALYSTID,

    ISADMIN

  FROM KM_ANALYST_MASTER

  WHERE UPPER(EMAIL) = UPPER(LOGIN_ID);

  

  SELECT MAX(EFFECTIVE_DATE) INTO EFFECTIVEDT FROM KM_SEC_DY_FACTORS;

  

  IF ISADMIN  <> 1 THEN

    OPEN RESULTSET FOR 

    SELECT KIU.SECURITY_CODE

    ,SM.SECURITY_NAME

    ,NVL(KSDF.PRICE,0) AS PRICE

    ,ISIN.SOURCE_SECURITY_CODE AS ISIN_CODE   

    ,S.SECTOR_NAME

    ,KAM.FIRSTNAME||' '|| SUBSTR(KAM.LASTNAME,1,1)||'.' AS ANALYST_NAME

    FROM KM_INVESTMENT_UNIVERSE KIU

    INNER JOIN SECURITY_MASTER SM ON SM.SECURITY_CODE = KIU.SECURITY_CODE 

    INNER JOIN SECURITY_CODE_BBISIN_INTMDT ISIN

    ON SM.SECURITY_CODE = ISIN.BM_CODE

     INNER JOIN(SELECT ANALYST_ID,

      SECURITY_CODE

    FROM KM_ANALYST_SECURITY_MAPPING

    WHERE ANALYST_ID  = ANALYSTID

    ) KASM ON KASM.SECURITY_CODE = KIU.SECURITY_CODE

    LEFT JOIN KM_SEC_DY_FACTORS KSDF 

    ON KIU.SECURITY_CODE = KSDF.SECURITY_CODE 

    INNER JOIN SECURITY_SECTOR_MAPPING SSM

    ON SSM.SECURITY_CODE = KASM.SECURITY_CODE

    INNER JOIN SECTORS S

    ON SSM.SECTOR_ID = S.SECTOR_ID   

     INNER JOIN 

    (

      SELECT FIRSTNAME,LASTNAME,ANALYST_ID FROM KM_ANALYST_MASTER WHERE ISADMIN <> 1

    ) KAM

    ON KAM.ANALYST_ID = KASM.ANALYST_ID

    where KSDF.EFFECTIVE_DATE = EFFECTIVEDT;

  ELSE

    OPEN RESULTSET FOR 

    SELECT KIU.SECURITY_CODE

    ,SM.SECURITY_NAME 

    ,NVL(KSDF.PRICE,0) AS PRICE

    ,ISIN.SOURCE_SECURITY_CODE AS ISIN_CODE   

    ,S.SECTOR_NAME

    ,KAM.FIRSTNAME||' '|| SUBSTR(KAM.LASTNAME,1,1)||'.' AS ANALYST_NAME

    FROM KM_INVESTMENT_UNIVERSE KIU 

    INNER JOIN SECURITY_MASTER SM ON SM.SECURITY_CODE = KIU.SECURITY_CODE

    INNER JOIN SECURITY_CODE_BBISIN_INTMDT ISIN

    ON SM.SECURITY_CODE = ISIN.BM_CODE

    LEFT JOIN KM_SEC_DY_FACTORS KSDF 

    ON KIU.SECURITY_CODE = KSDF.SECURITY_CODE 

    INNER JOIN KM_ANALYST_SECURITY_MAPPING KASM ON KASM.SECURITY_CODE = KIU.SECURITY_CODE

    INNER JOIN SECURITY_SECTOR_MAPPING SSM

    ON SSM.SECURITY_CODE = KASM.SECURITY_CODE

    INNER JOIN SECTORS S

    ON SSM.SECTOR_ID = S.SECTOR_ID    

     INNER JOIN 

    (

      SELECT FIRSTNAME,LASTNAME,ANALYST_ID FROM KM_ANALYST_MASTER WHERE ISADMIN = 1

    ) KAM

    ON KAM.ANALYST_ID = KASM.ANALYST_ID

    where KSDF.EFFECTIVE_DATE = EFFECTIVEDT;

  END IF;

END SP_FE_IDEAVIEW_SECURITIES;

