PROCEDURE SP_FE_SPEC_FIDX_RET(FUNDID IN NUMBER,INDEXID IN NUMBER,EFF_DATE IN DATE,RESULTSET OUT SYS_REFCURSOR)

AS

FUND_RET NUMBER(25,10);

INDEX_RET NUMBER(25,10);

BEGIN



  FUND_RET := NULL;

  INDEX_RET := NULL;

  SELECT NVL(MIN(RET_1D),99.99) INTO FUND_RET FROM fund_nav_returns WHERE FUND_ID = FUNDID AND TRUNC(effective_date) = EFF_DATE; 

  SELECT NVL(MIN(RET_1D),0) INTO INDEX_RET FROM index_returns WHERE INDEX_ID = INDEXID AND TRUNC(EFFECTIVE_DATE) = EFF_DATE;



  IF FUND_RET = 99.99 THEN

    SELECT NVL(MIN(P_NAV_RET),0) AS P_NAV_RET INTO FUND_RET

    FROM 

    FUND_ATTRIBUTED_DATA FAD

    INNER JOIN 

    REPORT_REFERENCES RR

    ON FAD.REPORT_ID = RR.REPORT_ID

    WHERE RR.FUND_ID = FUNDID AND TRUNC(RR.TO_DATE) = EFF_DATE;

    

  END IF;  

    

OPEN RESULTSET FOR 



  SELECT FUND_RET AS FUND_1D, INDEX_RET AS INDEX_1D FROM DUAL;



END;