PROCEDURE SP_FE_LIVE_TURNOVER_RAT 

(FUNDID IN NUMBER, TO_DATE IN DATE, RESULTSET OUT SYS_REFCURSOR) 

AS

	FROM_DATE DATE;

BEGIN

	SELECT ADD_MONTHS (TO_DATE, - 12)

	INTO FROM_DATE

	FROM DUAL;





	OPEN RESULTSET FOR --

	 SELECT NVL (ROUND (MIN (TO_VAL_TEMP), 5), 0) AS TURNOVER

	  FROM (SELECT SALE_PURCHASE_FLAG, AMOUNT, AVGAUM, CASE

														   WHEN AVGAUM <> 0 THEN AMOUNT / AVGAUM

														   ELSE 0

													   END AS TO_VAL_TEMP

			FROM (	SELECT TD.SALE_PURCHASE_FLAG, SUM (ABS (TD.CONSIDERATION)) AS AMOUNT

					  FROM TRANSACTION_DATA TD, SECURITY_MASTER  SM

					  WHERE TD.TRANSACTION_TYPE_ID = 1

						AND TD.FUND_ID = FUNDID

						AND TD.SECURITY_CODE = SM.SECURITY_CODE

						AND SM.INSTRUMENT_TYPE_ID NOT IN (7, 17) -- 7: CBLO, 17: REPO

						AND TRUNC (TRANSACTION_DATE) >= TRUNC (FROM_DATE)

						AND TRUNC (TRANSACTION_DATE) <= TRUNC (TO_DATE)

						AND SALE_PURCHASE_FLAG = 0

					  GROUP BY TD.SALE_PURCHASE_FLAG

					UNION ALL

					SELECT TD.SALE_PURCHASE_FLAG, SUM (ABS (TD.CONSIDERATION)) AS AMOUNT

					FROM TRANSACTION_DATA TD, SECURITY_MASTER  SM

					WHERE TD.TRANSACTION_TYPE_ID = 1

						AND TD.FUND_ID = FUNDID

						AND TD.SECURITY_CODE = SM.SECURITY_CODE

						AND SM.INSTRUMENT_TYPE_ID NOT IN (7, 17) -- 7: CBLO, 17: REPO

						AND TRUNC (TRANSACTION_DATE) >= TRUNC (FROM_DATE)

						AND TRUNC (TRANSACTION_DATE) <= TRUNC (TO_DATE)

						AND SALE_PURCHASE_FLAG = 1

					GROUP BY TD.SALE_PURCHASE_FLAG

				 ), (SELECT AVG (NAV) AS AVGAUM

					FROM FUND_NAV

					WHERE FUND_ID = FUNDID

					  AND TRUNC (VALUE_DATE) >= TRUNC (FROM_DATE)

					  AND TRUNC (VALUE_DATE) <= TRUNC (TO_DATE)

					)

		   );



END;