PROCEDURE SP_KM_INSERT_REPORT_DATA (SECURITYCODE IN VARCHAR2 ,REPORTTYPE IN NUMBER,

RECOMMEND IN NUMBER,ANALYSTID IN VARCHAR2,ISIN_CODE IN VARCHAR2,RESEARCH_DT_PRICE IN NUMBER,

TARG_PRICE IN NUMBER,LOGINID in VARCHAR2,EFFDATE in VARCHAR2,RESULTSET OUT NUMBER) 

AS



CNT NUMBER;



BEGIN       

          INSERT INTO KM_REPORT_DATA(SECURITY_CODE, ANALYST_ID, REPORT_TYPE_ID, RECO_ID, 

          RESEARCH_DATE,ISIN, ACT_INACT_FLAG,TARGET_PRICE,RESEARCH_DATE_PRICE,INSERTED_DATE,UPDATED_BY)          

          VALUES(SECURITYCODE, ANALYSTID, REPORTTYPE,RECOMMEND,SYSDATE,ISIN_CODE,1,TARG_PRICE,RESEARCH_DT_PRICE,SYSDATE,LOGINID)

          returning Report_ID into RESULTSET;         

          

          SELECT COUNT(*) INTO CNT FROM KM_SEC_DY_FACTORS WHERE SECURITY_CODE = SECURITYCODE AND EFFECTIVE_DATE = EFFDATE;

          IF(CNT = 1) THEN

          UPDATE KM_SEC_DY_FACTORS SET TARGET_PRICE = TARG_PRICE WHERE SECURITY_CODE = SECURITYCODE AND EFFECTIVE_DATE = EFFDATE; 

          END IF;              

                      

          --SELECT MAX(REPORT_ID) INTO RESULTSET FROM KM_REPORT_DATA;

          

END SP_KM_INSERT_REPORT_DATA;

