PROCEDURE SP_LDG_CORPACTEXC_XLS
CURR_DATE DATE;
CURRCOUNT NUMBER;
ERRMSG varchar2(200);
--ERRCODE varchar2(20);
BEGIN
  
  SELECT CURRDATADATE INTO CURR_DATE FROM DAILY_PROCESS_STATS WHERE UPPER(PROCESS_NAME) = 'ETL STAGE 1';
  
  SELECT COUNT(*) INTO CURRCOUNT
  FROM BSENSECA$@"VALAT_LDGDOM_LNKP"
  WHERE TO_DATE("EFFECTIVE_DATE", 'DD-MM-YYYY') = TO_DATE(CURR_DATE, 'DD-MM-YYYY');
  
  IF CURRCOUNT <> 0 THEN 
  
      INSERT INTO CORPORATE_ACTIONS_EXC_SRC (EFFECTIVE_DATE,CA_TYPE,COMPANY_NAME,BSE_NSE_CODE,
      ISIN,EX_DATE,DIVIDEND_RATE,DIVIDEND_PER_SHARE,ADD_UPD_FLAG, NEW_RATIO, OLD_RATIO, OLD_ISIN,OLD_NAME,SECURITY_TYPE)
      SELECT "EFFECTIVE_DATE","CA_TYPE",replace("COMPANY_NAME",'''',''),"BSE_NSE_CODE",
      "ISIN","EX_DATE","DIVIDEND_RATE","DIVIDEND_PER_SHARE","ADD_UPD_FLAG", "NEW_RATIO", "OLD_RATIO", "OLD_ISIN",
      "OLD_NAME","SECURITY_TYPE"
      FROM BSENSECA$@"VALAT_LDGDOM_LNKP" WHERE
      TO_DATE("EFFECTIVE_DATE", 'DD-MM-YYYY') = TO_DATE(CURR_DATE, 'DD-MM-YYYY')
      AND TO_DATE("EFFECTIVE_DATE", 'DD-MM-YYYY') NOT IN (SELECT TRUNC(EFFECTIVE_DATE) FROM CORPORATE_ACTIONS_EXC_SRC)
      AND REPLACE("EX_DATE",' ','') IS NOT NULL 
      AND REPLACE("COMPANY_NAME",' ','') IS NOT NULL
      AND REPLACE("CA_TYPE",' ','') IS NOT NULL
      AND REPLACE("ISIN",' ','') IS NOT NULL;
      
  END IF;

EXCEPTION 
WHEN OTHERS THEN
ERRMSG:=substr(SQLERRM, 1, 200);
--ERRCODE:=SQLCODE;
  
UPDATE DAILY_PROCESS_STATS SET STATUS = 'Corp Actions Exchange Src Load - '||ERRMSG  where UPPER(PROCESS_NAME) = 'ETL STAGE 1';

END;