PROCEDURE SP_LDG_INDEXDATATRI_XLS AS



CURR_DATE DATE;



BEGIN

SELECT CURRDATADATE INTO CURR_DATE FROM DAILY_PROCESS_STATS WHERE UPPER(PROCESS_NAME) = 'ETL STAGE 1'; -- TO_DATE(EFFECTIVE_DATE", 'DD-Mon-YY') = TO_DATE(CURR_DATE, 'DD-Mon-YY')