PROCEDURE SP_TRANSF_MODEL_BATCH

AS

START_DATE DATE;

END_DATE DATE;

CURSOR FUNDCUR IS SELECT EFFECTIVE_DATE FROM BUSINESS_CALENDAR WHERE BUSINESSDAY_FLAG = 1 AND (EFFECTIVE_DATE  >= '15-OCT-18' AND EFFECTIVE_DATE <='5-DEC-18'); 

BEGIN



FOR FDS IN FUNDCUR

LOOP



    --SP_TRANSF_TRANS_MODEL_V1(FDS.EFFECTIVE_DATE);

    SP_TRANSF_COPY_MODTOMAIN_BATCH(FDS.EFFECTIVE_DATE);

END LOOP;

END;