PROCEDURE SP_TRANSF_CREATE_TRANS_MODEL

AS

CURR_DATE DATE;

EFFECT_DATE DATE;

PREV_DATE DATE;

MISSING_PRICE_COUNT NUMBER;

MODEL_AUM NUMBER(25,10);

MISSING_PRICE_EXCEPTION EXCEPTION;

MODEL_DIVIDEND NUMBER(25,10);

HLDCOUNT NUMBER;

ERRMSG varchar2(200);

MISSING_PRICE_SECURITY VARCHAR2(5000);

CURSOR FUNDCUR IS SELECT FUND_ID FROM FUNDS WHERE NVL(TRANSACTION_MODEL_FLAG,0) = 1 AND NVL(MODEL_FLAG,0) = 1 AND ACTIVE_INACTIVE_FLAG <> '0' ORDER BY FUND_ID;



BEGIN



DELETE FROM temp_missing_prices;



--GETTING THE DATE FOR WHICH HOLDINGS IS PRESENT

SELECT CURRDATADATE INTO CURR_DATE FROM DAILY_PROCESS_STATS WHERE UPPER(PROCESS_NAME) = 'ETL STAGE 2';



--CURR_DATE := '15-NOV-17';



--GETTING THE DATE FOR WHICH THE TRANSACTIONS WILL BE PLACED

SELECT MIN(EFFECTIVE_DATE) INTO EFFECT_DATE FROM BUSINESS_CALENDAR WHERE BUSINESSDAY_FLAG = 1 AND TRUNC(EFFECTIVE_DATE) > TRUNC(CURR_DATE);



--GETTING PREVIOUS HOLDING DATE

SELECT MAX(EFFECTIVE_DATE) INTO PREV_DATE FROM BUSINESS_CALENDAR WHERE BUSINESSDAY_FLAG = 1 AND TRUNC(EFFECTIVE_DATE) < TRUNC(CURR_DATE);





INSERT INTO TEMP_MISSING_PRICES (SECURITY_CODE, SECURITY_NAME)

SELECT A.SECURITY_CODE, SM.SECURITY_NAME FROM

(

    SELECT SECURITY_CODE FROM

    (

        SELECT DISTINCT SECURITY_CODE AS SECURITY_CODE FROM FUND_HOLDINGS_MODEL FH, FUNDS F WHERE F.FUND_ID= FH.FUND_ID

        AND TRUNC(FH.EFFECTIVE_DATE)=TRUNC(CURR_DATE) AND NVL(F.ACTIVE_INACTIVE_FLAG,0)<>0 AND NVL(F.MODEL_FLAG,0)=0 

        AND NVL(F.TRANSACTION_MODEL_FLAG,0)=1 AND FH.SECURITY_CODE<>'INCASH000001'

    )

    MINUS

    (

        SELECT DISTINCT SECURITY_CODE AS SECURITY_CODE 

        FROM 

        SECURITY_CLOSEPRICES 

        WHERE TRUNC(PRICE_DATE)=TRUNC(CURR_DATE)

    )

)A,SECURITY_MASTER SM WHERE A.SECURITY_CODE= SM.SECURITY_CODE;



SELECT COUNT(*) INTO MISSING_PRICE_COUNT FROM TEMP_MISSING_PRICES;

  

IF (MISSING_PRICE_COUNT > 0) THEN

    SELECT STRING_AGGREGATE('SELECT SECURITY_NAME FROM TEMP_MISSING_PRICES') INTO MISSING_PRICE_SECURITY FROM DUAL;

    RAISE MISSING_PRICE_EXCEPTION;

END IF;





FOR FDS IN FUNDCUR

LOOP



SELECT COUNT(*) INTO HLDCOUNT FROM FUND_HOLDINGS_MODEL WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) =  TRUNC(CURR_DATE);



    IF HLDCOUNT >0 THEN

    

    --TAKING HOLDINGS TO EOD PRICE

    MERGE INTO FUND_HOLDINGS_MODEL FHMEOD

    USING

    (

        SELECT FHM.SECURITY_CODE,EFFECTIVE_DATE,FHM.QUANTITY * NVL(NSEP.CLOSEP,BSEP.CLOSEP) AS MTM,NVL(NSEP.CLOSEP,BSEP.CLOSEP) AS PRICE FROM

        (

            SELECT * FROM FUND_HOLDINGS_MODEL WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE) AND SECURITY_CODE <> 'INCASH000001'

        )FHM

        LEFT JOIN

        (

            SELECT SECURITY_CODE,CLOSEP FROM SECURITY_CLOSEPRICES WHERE TRUNC(PRICE_DATE) = TRUNC(CURR_DATE) AND EXCHANGE_ID = 1

        )NSEP

        ON FHM.SECURITY_CODE = NSEP.SECURITY_CODE

        LEFT JOIN

        (

            SELECT SECURITY_CODE,CLOSEP FROM SECURITY_CLOSEPRICES WHERE TRUNC(PRICE_DATE) = TRUNC(CURR_DATE) AND EXCHANGE_ID = 2

        )BSEP

        ON FHM.SECURITY_CODE = BSEP.SECURITY_CODE

    )FHM

    ON (FHMEOD.SECURITY_CODE = FHM.SECURITY_CODE AND FHMEOD.EFFECTIVE_DATE = FHM.EFFECTIVE_DATE)

    WHEN MATCHED THEN

    UPDATE SET FHMEOD.MTM_VALUE = FHM.MTM,FHMEOD.PRICE = FHM.PRICE;

    

    

    --DIVIDEND ADJUSTMENT

    SELECT NVL(SUM(FHM.QUANTITY * OFFER_PRICE),0) INTO MODEL_DIVIDEND FROM

    (

        SELECT * FROM 

        FUND_HOLDINGS_MODEL 

        WHERE FUND_ID = FDS.FUND_ID AND (EFFECTIVE_DATE) = TRUNC(PREV_DATE)

    )FHM

    INNER JOIN

    (

        SELECT * FROM 

        MTM_AFFECTING_CAS

        WHERE CORPORATE_ACTION_TYPE_ID = 1 AND TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE)

    )MAC

    ON FHM.SECURITY_CODE = MAC.SECURITY_CODE;

    

    

    --CALCULATING AUM FOR THE EOD HOLDINGS

    SELECT SUM(MTM_VALUE) INTO MODEL_AUM FROM FUND_HOLDINGS_MODEL WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE);

    

    --CALCULATING WEIGHTS FOR THE EOD HOLDINGS

    UPDATE FUND_HOLDINGS_MODEL SET WEIGHTS =  ROUND(MTM_VALUE/(MODEL_AUM+MODEL_DIVIDEND),8) WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE); 

    

    

    UPDATE FUND_HOLDINGS_MODEL SET WEIGHTS =  ROUND(MTM_VALUE/(MODEL_AUM+MODEL_DIVIDEND),8) 

    WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE) AND SECURITY_CODE='INCASH000001'; 

    

    

    --INSERTING HOLDING FOR THE EFFECTIVE DATE(THE DAY TRANSACTIONS WILL BE PLACED)

    INSERT INTO FUND_HOLDINGS_MODEL(FUND_ID,EFFECTIVE_DATE,SECURITY_CODE,QUANTITY,MTM_VALUE,PRICE,WEIGHTS)

    SELECT FUND_ID,TRUNC(EFFECT_DATE),SECURITY_CODE,QUANTITY,MTM_VALUE,PRICE,WEIGHTS

    FROM FUND_HOLDINGS_MODEL

    WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE) ;

    

    

    --ADJUSTING CORPORATE ACTIONS FOR EFFECT_DATE

    MERGE INTO FUND_HOLDINGS_MODEL FHM

    USING

    (

        SELECT FHM.FUND_ID,FHM.SECURITY_CODE,FHM.EFFECTIVE_DATE,(NVL(MAC.NUMERATOR,1)/NVL(MAC.DENOMINATOR,1)) AS RATIO FROM

        (

            SELECT * FROM 

            FUND_HOLDINGS_MODEL 

            WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) = TRUNC(EFFECT_DATE)

        )FHM

        INNER JOIN

        (

            SELECT * FROM 

            MTM_AFFECTING_CAS

            WHERE CORPORATE_ACTION_TYPE_ID IN (2,3) AND TRUNC(EFFECTIVE_DATE) = TRUNC(EFFECT_DATE)

        )MAC

        ON FHM.SECURITY_CODE = MAC.SECURITY_CODE

    )CORP

    ON (FHM.SECURITY_CODE = CORP.SECURITY_CODE AND FHM.EFFECTIVE_DATE = CORP.EFFECTIVE_DATE AND FHM.FUND_ID = CORP.FUND_ID)

    WHEN MATCHED THEN 

    UPDATE SET FHM.PRICE = ROUND(RATIO * PRICE,8);

    

    --UPDATING THE QUANTITY BASED ON THE ADJUSTED CORPORATE ACTION

    UPDATE FUND_HOLDINGS_MODEL SET QUANTITY = ROUND(MTM_VALUE/PRICE,0) WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) = TRUNC(EFFECT_DATE);

    

    --UPDATING THE MTM BASED ON THE NEW QUANTITY (ROUNDED)

    UPDATE FUND_HOLDINGS_MODEL SET MTM_VALUE = QUANTITY * PRICE WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) = TRUNC(EFFECT_DATE);

    

    --CALCULATING THE NEW AUM

    SELECT SUM(MTM_VALUE) INTO MODEL_AUM

    FROM FUND_HOLDINGS_MODEL

    WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) = TRUNC(EFFECT_DATE);

    

    --CALCULATING THE NEW WEIGHTS

    UPDATE FUND_HOLDINGS_MODEL SET WEIGHTS = ROUND(MTM_VALUE/MODEL_AUM,8) WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE) = TRUNC(EFFECT_DATE);

    

    --INSERTING THE UPDATED HOLDINGS TO FUND_HOLDINGS_MODEL_BOD

    INSERT INTO FUND_HOLDINGS_MODEL_BOD (FUND_ID, EFFECTIVE_DATE, SECURITY_CODE, QUANTITY, MTM_VALUE, PRICE, OPTION_POSITION,WEIGHTS)

    SELECT FUND_ID, EFFECTIVE_DATE, SECURITY_CODE, QUANTITY, MTM_VALUE, PRICE, OPTION_POSITION,WEIGHTS

    FROM FUND_HOLDINGS_MODEL 

    WHERE FUND_ID = FDS.FUND_ID AND TRUNC(EFFECTIVE_DATE)=TRUNC(EFFECT_DATE);

    

    END IF;

END LOOP;

COMMIT;



EXCEPTION 

WHEN MISSING_PRICE_EXCEPTION THEN

UPDATE DAILY_PROCESS_STATS SET STATUS = 'Model Transaction Portfolio - Price Missing for '||MISSING_PRICE_SECURITY  where UPPER(PROCESS_NAME) = 'ETL STAGE 2 OFFSHORE';

COMMIT;

WHEN OTHERS THEN

ERRMSG:=substr(SQLERRM, 1, 200);

--ERRCODE:=SQLCODE;

UPDATE DAILY_PROCESS_STATS SET STATUS = 'Model Transaction Portfolio - '||ERRMSG  where UPPER(PROCESS_NAME) = 'ETL STAGE 2 OFFSHORE';

COMMIT;



END;