PROCEDURE SP_TRANSF_HOLDBAL_MAIN (CURRDATE IN DATE) 

as

CURR_DATE DATE;

PREV_DATE DATE;

CURRCOUNT NUMBER;

ERRTRANSEC VARCHAR2(4000);

ERRMSG varchar2(200);



cursor fundcur is select funds.fund_id from funds WHERE normal_flag <> 1 and active_inactive_flag <> '0' order by fund_id;

--cursor fundcur is select funds.fund_id from funds WHERE fund_id=76;



BEGIN

CURR_DATE := CURRDATE;



 EXECUTE IMMEDIATE 'TRUNCATE TABLE ERR_TRAN_NEW';



FOR FDS IN FUNDCUR

LOOP

INSERT INTO err_tran_new(FUND_ID,SECURITY_CODE,FROM_DATE,TO_DATE,QUANTITY_FROM,QUANTITY_TO,QUANTITY_TRAN)

SELECT 

  FDS.FUND_ID as Fund_ID,

  CASE WHEN CURRDATE.security_code IS NOT NULL THEN CURRDATE.security_code ELSE

  CASE WHEN PREVDATE.security_code IS NOT NULL THEN PREVDATE.security_code ELSE 

  TXN.security_code END END AS SECURITY_CODE      ,

  PREVDATE.PREV_DATE, CASE WHEN nvl(PREVDATE.CURR_DATE,CURRDATE.effective_date) IS NULL THEN TXN.transaction_date

  ELSE nvl(PREVDATE.CURR_DATE,CURRDATE.effective_date) END AS CURR_DATE,  NVL(PREVDATE.prev_QTY,0) AS PREV_QTY

  , NVL(CURRDATE.quantity,0) AS CURR_QTY, NVL(TXN.TXN_QUANT,0) AS TXN_QTY

  

   FROM

  (

    SELECT FUND_ID, FH1.SECURITY_CODE, CASE WHEN option_position='S' THEN ABS(QUANTITY) *-1 ELSE ABS(CAST(NVL(quantity,0) AS NUMBER(25,10))) * (CAST(NVL(denominator,1) AS NUMBER(25,10)) / CAST(NVL(numerator,1)AS NUMBER(25,10)) )END AS PREV_QTY, 

    PREV_DATE, CURR_DATE FROM

    (

      SELECT FUND_ID,SECURITY_CODE, option_position,QUANTITY, effective_date AS PREV_DATE, 

      (

          SELECT MIN(EFFECTIVE_DATE) FROM BUSINESS_CALENDAR BC WHERE BC.BUSINESSDAY_FLAG=1

          AND BC.EFFECTIVE_DATE>FH.effective_date AND TRUNC(FH.effective_date)<TRUNC(CURRDATE)

      ) AS CURR_DATE

      FROM fund_holdings FH WHERE FUND_ID=FDS.FUND_ID 

    ) FH1

    LEFT JOIN MTM_AFFECTING_CAS MTM

    ON (FH1.security_code = MTM.security_code AND MTM.CORPORATE_ACTION_TYPE_ID IN (2,3,4) 

    AND TRUNC(MTM.EFFECTIVE_DATE) = TRUNC(FH1.CURR_DATE))

  ) PREVDATE

  FULL OUTER JOIN

  (

    SELECT QUANTITY,effective_date,FUND_ID,SECURITY_CODE FROM fund_holdings

    WHERE FUND_ID=FDS.FUND_ID

  ) CURRDATE

  ON (CURRDATE.FUND_ID=PREVDATE.FUND_ID AND CURRDATE.effective_date=PREVDATE.CURR_DATE AND CURRDATE.SECURITY_CODE=PREVDATE.SECURITY_CODE)

  FULL OUTER JOIN

  (

      SELECT FUND_ID, transaction_date,SECURITY_CODE, SUM( CASE WHEN sale_purchase_flag= 0 THEN -1*(QUANTITY) WHEN sale_purchase_flag=1 THEN QUANTITY END) AS TXN_QUANT

      FROM transaction_data WHERE FUND_ID=FDS.FUND_ID and transaction_data.transaction_type_id=1 GROUP BY FUND_ID, transaction_date,SECURITY_CODE

  )

  TXN

  ON TXN.transaction_date=nvl(CURRDATE.effective_date,PREVDATE.CURR_DATE) AND (TXN.SECURITY_CODE=NVL(CURRDATE.SECURITY_CODE,PREVDATE.SECURITY_CODE) );

COMMIT;

END LOOP;

EXCEPTION 

WHEN OTHERS THEN

ERRMSG:=substr(SQLERRM, 1, 200);

--ERRCODE:=SQLCODE;

UPDATE DAILY_PROCESS_STATS SET STATUS = 'Transactions Check - '||ERRMSG  where UPPER(PROCESS_NAME) = 'ETL STAGE 2';



END SP_TRANSF_HOLDBAL_MAIN;