PROCEDURE SP_TRANSF_COPY_MODELTOMAIN AS

CURR_DATE DATE;

DATAREADY NUMBER;

PREV_DATE DATE;

ERRMSG varchar2(2000);

BEGIN



SELECT CURRDATADATE INTO CURR_DATE FROM DAILY_PROCESS_STATS WHERE UPPER(PROCESS_NAME) = 'ETL STAGE 2';



--CHECK TO SEE IF DATA EXISTS FOR CURR_DATE

SELECT COUNT(*) INTO DATAREADY FROM FUND_HOLDINGS_MODEL WHERE TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE);



--PREV_DATE

SELECT Max(effective_date) INTO PREV_DATE FROM business_calendar WHERE eq_bd_flag=1 and trunc(effective_date)<trunc(CURR_DATE);



IF DATAREADY<>0 THEN

--INSERTING MODEL HOLDINGS TO MAIN

INSERT INTO FUND_HOLDINGS(FUND_ID,EFFECTIVE_DATE,SECURITY_CODE,QUANTITY,MTM_VALUE,OPTION_POSITION,PUR_VALUE,AMMORTISED_BOOK_COST,WEIGHT)

SELECT FUND_ID,EFFECTIVE_DATE,SECURITY_CODE,QUANTITY,MTM_VALUE,NULL,NULL,NULL,WEIGHTS

FROM 

FUND_HOLDINGS_MODEL

WHERE TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE); 





--INSERTING MODEL NAV TO MAIN

INSERT INTO FUND_NAV(FUND_ID,VALUE_DATE,NAV)

SELECT FUND_ID,EFFECTIVE_DATE,SUM(MTM_VALUE) 

FROM 

FUND_HOLDINGS_MODEL

WHERE TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE)

GROUP BY FUND_ID,EFFECTIVE_DATE;



--INSERTING MODEL TRANSACTIONS TO MAIN

INSERT INTO TRANSACTION_DATA(FUND_ID,SECURITY_CODE,TRANSACTION_DATE,TRANSACTION_TYPE_ID,SALE_PURCHASE_FLAG,QUANTITY,TRANSACTION_PRICE,CONSIDERATION)

SELECT FUND_ID,SECURITY_CODE,TRANSACTION_DATE,TRANSACTION_TYPE_ID,SALE_PURCHASE_FLAG,QUANTITY,TRANSACTION_PRICE,CONSIDERATION

FROM 

TRANSACTION_DATA_MODEL

WHERE TRUNC(TRANSACTION_DATE) = TRUNC(CURR_DATE);



INSERT INTO fund_security_closeprices  (fund_id, price_date, security_code, closep) 

select FUND_ID, EFFECTIVE_DATE, SECURITY_CODE, (MTM_VALUE/QUANTITY) FROM FUND_HOLDINGS_MODEL

WHERE SECURITY_CODE<>'INCASH000001' AND TRUNC(EFFECTIVE_DATE)= TRUNC(CURR_DATE);



--INSERTING CASH TRANSACTION

INSERT INTO TRANSACTION_DATA (FUND_ID, SECURITY_CODE, TRANSACTION_DATE, TRANSACTION_TYPE_ID, SALE_PURCHASE_FLAG, QUANTITY, TRANSACTION_PRICE, CONSIDERATION)

SELECT FUND_ID, SECURITY_CODE, TRUNC(CURR_DATE), TRANSACTION_TYPE_ID, 0, 1, TRANSAMT, TRANSAMT

FROM

(

    SELECT MTMTAB.FUND_ID, MTMTAB.SECURITY_CODE, NVL(NETCASH,0) + NVL(TRANSVAL,0) AS TRANSAMT

    FROM

    (

        SELECT CURRMTM.FUND_ID AS FUND_ID, CURRMTM.SECURITY_CODE AS SECURITY_CODE, NVL(CURRMTM_VAL,0) - NVL(PREVMTM_VAL,0) AS NETCASH

        FROM

        (

            SELECT FUND_ID, SECURITY_CODE, MTM_VALUE AS CURRMTM_VAL

            FROM FUND_HOLDINGS WHERE TRUNC(EFFECTIVE_DATE) = TRUNC(CURR_DATE)

            AND UPPER(SECURITY_CODE) = 'INCASH000001'

        ) CURRMTM

        LEFT OUTER JOIN

        (

            SELECT FUND_ID, SECURITY_CODE, MTM_VALUE AS PREVMTM_VAL

            FROM FUND_HOLDINGS WHERE TRUNC(EFFECTIVE_DATE) = TRUNC(PREV_DATE)

            AND UPPER(SECURITY_CODE) = 'INCASH000001'

        ) PREVMTM

        ON (CURRMTM.FUND_ID = PREVMTM.FUND_ID AND UPPER(CURRMTM.SECURITY_CODE) = UPPER(PREVMTM.SECURITY_CODE))

    ) MTMTAB       

    LEFT OUTER JOIN 

    (

        SELECT FUND_ID, SUM(NVL(TRAN_COST,0)+NVL(DIVIDENDBONUS_PAYOUT,0)) AS TRANSVAL, TRANSACTION_TYPE_ID

        FROM 

        (

            SELECT FUND_ID, SECURITY_CODE, 

            (CASE WHEN (UPPER(TRANSACTION_TYPE_DESCRIPTION) <> 'DIVIDEND' and UPPER(TRANSACTION_TYPE_DESCRIPTION) <> 'BONUS') THEN (CASE WHEN SALE_PURCHASE_FLAG = 0 THEN -1*(Quantity*Transaction_Price) ELSE (Quantity*Transaction_Price) END) ELSE 0 END) AS TRAN_COST,

            (CASE WHEN (UPPER(TRANSACTION_TYPE_DESCRIPTION) = 'DIVIDEND' or UPPER(TRANSACTION_TYPE_DESCRIPTION) = 'BONUS') THEN (CASE WHEN SALE_PURCHASE_FLAG = 0 THEN -1*(Consideration) ELSE (Consideration) END) ELSE 0 END) AS DividendBonus_Payout

            FROM TRANSACTION_DATA TD

            INNER JOIN TRANSACTIONS 

            ON (TD.transaction_type_id = transactions.transaction_type_id)

            WHERE trunc(TRANSACTION_DATE) = TRUNC(CURR_DATE)

        ) TEMP, TRANSACTIONS

        WHERE UPPER(TRANSACTION_TYPE_DESCRIPTION) = 'SUBSCRIPTIONS/REDEMPTIONS'

        GROUP BY Fund_ID, TRANSACTION_TYPE_ID) TDATA

        ON (TDATA.FUND_ID = MTMTAB.FUND_ID)

    ) TRANSD, TRANSACTIONS

WHERE UPPER(TRANSACTION_TYPE_DESCRIPTION) = 'SUBSCRIPTIONS/REDEMPTIONS';



--INSERTING INTO FUND_HOLDINGS_LIVE

  INSERT INTO FUND_HOLDINGS_LIVE (FUND_ID, EFFECTIVE_DATE, SECURITY_CODE, QUANTITY, MTM_VALUE, MTM_VALUE_P)

  SELECT fund_id,EFFECTIVE_DATE,security_code,QUANTITY,MTM_VALUE,MTM_VALUE

  FROM fund_holdings_model

  WHERE TRUNC(EFFECTIVE_DATE)= TRUNC(CURR_DATE);





END IF;



EXCEPTION

WHEN OTHERS THEN

ERRMSG:=substr(SQLERRM, 1, 200);

--ERRCODE:=SQLCODE;

UPDATE DAILY_PROCESS_STATS SET STATUS = 'Model Transaction Portfolio copy - '||ERRMSG  where UPPER(PROCESS_NAME) = 'ETL STAGE 2 OFFSHORE';

COMMIT;









END;