PROCEDURE SP_UPDATE_ANALYST_REPORT (

    SECURITYCODE IN VARCHAR2,

    REPORTID     IN NUMBER,

    EFFECTIVE_DT IN VARCHAR2,

    RECOMMEND    IN NUMBER,

    LOGINID      IN VARCHAR2,

    TP           IN NUMBER)

AS

BEGIN

  UPDATE KM_REPORT_DATA

  SET TARGET_PRICE = TP,

    RECO_ID        = RECOMMEND,

    UPDATED_BY     = LOGINID,

    UPDATED_DATE   = SYSDATE

  WHERE REPORT_ID  = REPORTID;

  UPDATE KM_SEC_DY_FACTORS

  SET TARGET_PRICE    = TP

  WHERE SECURITY_CODE = SECURITYCODE

  AND EFFECTIVE_DATE  = EFFECTIVE_DT;

END SP_UPDATE_ANALYST_REPORT;